function l(){if(window.o){window.o=false;clearTimeout(window.t);window.removeEventListener("mousemove",window.i,true);window.removeEventListener("keydown",window.u);if(window.l)window.l.remove();return}window.o=true;window.p={x:0,y:0};window.i=o=>window.p={x:o.clientX,y:o.clientY};window.addEventListener("mousemove",window.i,true);let n=5,e=false,i=5;function o(){if(!e){for(let o=0;o<i;o++){const t=document.elementFromPoint(window.p.x,window.p.y);if(t)t.click()}}if(window.o)window.t=setTimeout(o,n)}o();const t=document.createElement("div");Object.assign(t.style,{position:"fixed",right:"12px",bottom:"12px",zIndex:2147483647,padding:"6px 10px",background:"rgba(0,0,0,0.75)",color:"#fff",fontFamily:"system-ui",fontSize:"12px",borderRadius:"8px"});t.textContent="Click spamming • S pause/resume • + / - speed • Esc stop";document.body.appendChild(t);window.l=t;window.u=o=>{if(o.key==="Escape"){window.o=false;clearTimeout(window.t);window.removeEventListener("mousemove",window.i,true);window.removeEventListener("keydown",window.u);t.remove();return}if(o.key.toLowerCase()==="s"){e=!e;t.textContent=e?"Paused • S resume • Esc stop":"Click spamming • S pause/resume • + / - speed • Esc stop"}if(o.key==="+"||o.key==="="){n=Math.max(5,n-1)}if(o.key==="-"){n=Math.min(2e3,n+1)}};window.addEventListener("keydown",window.u)}function p(){const o=["#sidebar-wrap","#advert","#xrail","#middle-article-advert-container","#sponsored-recommendations","#around-the-web","#taboola-content",".ad",".advertisement",".GoogleActiveViewClass",".ad-slot",".ad-banner",".ad-anchored",".trc_rbox_outer",".OUTBRAIN","iframe","video","amp-ad","ins.adsbygoogle",'div[id^="google_ads_iframe"]'];const e=()=>{o.forEach(o=>{document.querySelectorAll(o).forEach(o=>o&&o.remove())})};e();setInterval(e,1500);if(window.MutationObserver){new MutationObserver(e).observe(document.documentElement||document.body,{childList:true,subtree:true})}let t=location.href;const n=(o,t)=>{const n=o[t];o[t]=function(){const o=n.apply(this,arguments);setTimeout(e,60);return o}};n(history,"pushState");n(history,"replaceState");window.addEventListener("popstate",()=>setTimeout(e,60));setInterval(()=>{if(location.href!==t){t=location.href;e()}},300);if(!document.getElementById("adBGoneBtn")){const i=document.createElement("button");i.id="adBGoneBtn";i.innerText="💥 Ad-B-Gone";Object.assign(i.style,{position:"fixed",top:"10px",right:"10px",zIndex:9999,padding:"8px",background:"red",color:"white",border:"none",borderRadius:"5px",cursor:"pointer"});i.onclick=e;document.body.appendChild(i)}console.log("Ad-B-Gone helper ready")}function b(){function o(o,t){function n(o,t){return t===0?o:n(t,o%t)}return o*t/n(o,t)}const t=document.body.clientWidth;const n=document.body.clientHeight;const e=document.createElement("div");e.id="dvd";e.style.cssText=`
    position: fixed;
    left: 0;
    top: 0;
    height: 60px;
    width: 136px;
    mask: url('https://upload.wikimedia.org/wikipedia/commons/9/9b/DVD_logo.svg');
    -webkit-mask: url('https://upload.wikimedia.org/wikipedia/commons/9/9b/DVD_logo.svg');
    background-repeat: no-repeat;
    background-size: 75px;
    background-position: center;
    background-color: #ff8800;
    z-index: 9999999999;
  `;document.body.insertBefore(e,document.body.firstChild);const i=document.createElement("div");i.style.cssText=`
    position: fixed;
    right: 10px;
    top: 10px;
    padding: 4px 8px;
    background: rgba(0,0,0,0.6);
    color: #fff;
    font: 14px/1 system-ui, Arial;
    border-radius: 6px;
    z-index: 1000000;
    pointer-events: none;
  `;document.body.appendChild(i);let d=Math.floor(Math.random()*(t-100));let s=Math.floor(Math.random()*(n-50));let r=1,a=1;const c=Math.max(2,Math.min(t,n)/200);const u=["#ff8800","#e124ff","#6a19ff","#ff2188"];let l=0;const p=e.clientWidth;const b=e.clientHeight;const w=o(t-p,n-b);let f=0;function m(){const o=[...u];o.splice(l,1);const t=Math.floor(Math.random()*o.length);l=t<l?t:t+1;return o[t]}function x(){if(s+b>=n||s<0){a*=-1;e.style.backgroundColor=m()}if(d+p>=t||d<0){r*=-1;e.style.backgroundColor=m()}d+=r*c;s+=a*c;e.style.left=d+"px";e.style.top=s+"px";f++;const o=w-f;i.textContent="Seconds to corner: "+(o/60).toFixed(1);if(o<=0)f=0;window.requestAnimationFrame(x)}window.requestAnimationFrame(x);document.addEventListener("keydown",o=>{if(!e)return;if(o.key==="1")e.style.display=e.style.display==="none"?"block":"none";if(o.key==="Escape"){e.remove();i.remove()}})}function w(t){if(!t||isNaN(t)||t<=0)return;for(let o=0;o<t;o++){window.open("about:blank","_blank")}}(function f(){const o="my-floater-unique-elm-98123";const t=document.getElementById(o);if(t){t.style.display=t.style.display==="none"?"block":"none";return}const a=document.createElement("div");a.id=o;Object.assign(a.style,{position:"fixed",right:"16px",bottom:"16px",zIndex:2147483647});document.documentElement.appendChild(a);const n=a.attachShadow({mode:"open"});const e=`:host{font-family:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial}.card{width:260px;background:rgba(255,255,255,0.96);color:#111;border-radius:12px;box-shadow:0 8px 30px rgba(0,0,0,0.25);padding:10px;backdrop-filter:blur(6px);border:1px solid rgba(0,0,0,0.06)}.header{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:8px}.title{font-weight:600;font-size:14px}.btn{display:block;width:100%;padding:8px 10px;margin:6px 0;border-radius:8px;cursor:pointer;border:1px solid rgba(0,0,0,0.08);background:#f6f6f7;font-size:13px;text-align:left}.btn:active{transform:translateY(1px)}.small{font-size:12px;color:#555;margin-top:6px}.close-x{cursor:pointer;padding:4px 6px;border-radius:6px;background:transparent;border:0;font-weight:700}
  `;const c=document.createElement("div");c.className="card";c.innerHTML=`
  <div class=header><div class=title>Quick Menu</div><button class=close-x title=Close>✕</button></div><button class=btn id=btn-clicker>Auto Clicker</button> <button class=btn id=btn-ads>Remove all ads</button> <button class=btn id=btn-dvd>A DVD Bounces around</button> <button class=btn id=btn-tab>Tab Opener</button> <button class=btn id=btn-scroll>Scroll to top</button> <button class=btn id=btn-dark>Toggle dark</button>
  `;const i=document.createElement("style");i.textContent=e;n.appendChild(i);n.appendChild(c);const d=o=>n.querySelector(o);d("#btn-clicker").addEventListener("click",async()=>{l()});d("#btn-tab").addEventListener("click",async()=>{w(prompt("How many tabs do you want to open?"))});d("#btn-dvd").addEventListener("click",async()=>{b()});d("#btn-ads").addEventListener("click",()=>{p()});d("#btn-scroll").addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});let s=false;d("#btn-dark").addEventListener("click",()=>{s=!s;const o=c;if(s){o.style.background="rgba(20,20,20,0.95)";o.style.color="#eee";o.style.border="1px solid rgba(255,255,255,0.04)"}else{o.style.background="rgba(255,255,255,0.96)";o.style.color="#111";o.style.border="1px solid rgba(0,0,0,0.06)"}});d(".close-x").addEventListener("click",()=>{a.remove()});(function u(){const o=c;let e=false,i=0,d=0,s=0,r=0;o.addEventListener("mousedown",o=>{const t=o.composedPath().some(o=>o.classList&&o.classList.contains&&o.classList.contains("header"));if(!t)return;e=true;i=o.clientX;d=o.clientY;s=parseFloat(getComputedStyle(a).right)||16;r=parseFloat(getComputedStyle(a).bottom)||16;o.preventDefault()});window.addEventListener("mousemove",o=>{if(!e)return;const t=o.clientX-i;const n=o.clientY-d;a.style.right=s-t+"px";a.style.bottom=r-n+"px"});window.addEventListener("mouseup",()=>{e=false})})();n.querySelector(".btn").focus();const r=setTimeout(()=>{try{a.remove()}catch(o){}},12e4)})();
